# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

WORKDIR /app

COPY . .

# Use --ignore-requires-python to bypass the Python version check in pyproject.toml
RUN pip install --no-cache-dir --ignore-requires-python .

CMD ["mcp", "run", "src/server.py"]
