[project]
name = "mcp-sol"
version = "0.1.0"
description = "Model Context Protocol Server for Solana Client"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["mcp[cli]>=1.2.0", "solana>=0.36.3", "solders>=0.23.0"]
